//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.20 at 02:16:48 PM CEST 
//


package services.app.carrequestservice.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the services.app.carrequestservice.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: services.app.carrequestservice.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllReqeustsByPublisherIdRequest }
     * 
     */
    public GetAllReqeustsByPublisherIdRequest createGetAllReqeustsByPublisherIdRequest() {
        return new GetAllReqeustsByPublisherIdRequest();
    }

    /**
     * Create an instance of {@link GetAllRequestsByPublisherIdResponse }
     * 
     */
    public GetAllRequestsByPublisherIdResponse createGetAllRequestsByPublisherIdResponse() {
        return new GetAllRequestsByPublisherIdResponse();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link Ad }
     * 
     */
    public Ad createAd() {
        return new Ad();
    }

}
